services:
  frontend:
    image: node:22
    working_dir: /app
    command: bash -c "yarn install && yarn dev"
    ports:
      - 8000:3000
    volumes:
      - ./frontend:/app

  # docker run --rm -it -v ${PWD}/express:/app -w /app node bash
  # yarn init -y
  # yarn add nodemon express cors sequelize sqlite3
  backend:
    image: node:22
    working_dir: /app
    command: bash -c "yarn install && yarn dev"
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
